language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.3"
    - LUA="lua 5.2"
    - LUA="lua 5.1"
    - LUA="luajit 2.1"
    - LUA="luajit 2.0"

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov-coveralls

install:
  - luarocks install --only-deps cassowary-scm-0.rockspec

script:
  - luacheck cassowary-scm-0.rockspec
  - busted -c

after_success:
  - luacov-coveralls -v

cache:
  directories:
    - $HOME/.cache/hererocks
