language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.3" PENLIGHT="luarocks"
    - LUA="lua 5.3" PENLIGHT="github"
    - LUA="lua 5.2" PENLIGHT="luarocks"
    - LUA="lua 5.2" PENLIGHT="github"
    - LUA="lua 5.1" PENLIGHT="luarocks"
    - LUA="lua 5.1" PENLIGHT="github"
    - LUA="luajit 2.1" PENLIGHT="luarocks"
    - LUA="luajit 2.1" PENLIGHT="github"
    - LUA="luajit 2.0" PENLIGHT="luarocks"
    - LUA="luajit 2.0" PENLIGHT="github"

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov-coveralls

install:
  - if [ "$PENLIGHT" = "luarocks" ]; then luarocks install penlight ; fi
  - if [ "$PENLIGHT" = "github" ]; then luarocks install https://raw.githubusercontent.com/stevedonovan/Penlight/master/penlight-scm-2.rockspec ; fi

script:
  - luacheck cassowary-scm-0.rockspec
  - busted -c

after_success:
  - luacov-coveralls -v

cache:
  directories:
    - $HOME/.cache/hererocks
