name: Busted

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
        penlightSource: ["penlight", "https://raw.githubusercontent.com/stevedonovan/Penlight/master/penlight-scm-2.rockspec"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v2
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v2
    - name: Setup dependencies
      run: |
        luarocks install busted
        luarocks install luacov-coveralls
        luarocks install ${{ matrix.penlightSource }}
    - name: Run Busted Tests
      run: busted -c -v
    - name: Report Test Coverage
      if: matrix.luaVersion == '5.3' && matrix.penlightSource == 'penlight' && success()
      continue-on-error: true
      run: luacov-coveralls -i cassowary -v -t "${{ secrets.LUACOV_TOKEN }}"
