name: Busted

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Lua
      uses: MilesChou/lua-action@v0.0.1
      with:
        args: docker-luarocks-install busted

# eval $(luarocks path)
# busted tests/
